name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        USER: ${{secrets.USER}}
        PASS: ${{secrets.PASS}}
      run: docker build . --file Dockerfile --tag priyankasatdive14:$(date +%s)
           docker login -u $USER -p $PASS
           docker push priyankasatdive14:$(date +%s)
